export const countryNames: Record<string, string> = {
  AED: "United Arab Emirates",
  AUD: "Australia",
  BND: "Brunei",
  CAD: "Canada",
  CHF: "Switzerland",
  CNY: "China",
  EGP: "Egypt",
  EUR: "Eurozone",
  GBP: "United Kingdom",
  HKD: "Hong Kong",
  IDR: "Indonesia",
  INR: "India",
  JPY: "Japan",
  KHR: "Cambodia",
  KRW: "South Korea",
  MMK: "Myanmar",
  NPR: "Nepal",
  NZD: "New Zealand",
  PHP: "Philippines",
  PKR: "Pakistan",
  SAR: "Saudi Arabia",
  SDR: "International Monetary Fund (IMF)",
  SGD: "Singapore",
  THB: "Thailand",
  TWD: "Taiwan",
  USD: "United States",
  VND: "Vietnam",
};
